name: autoloader
authors:
    - name: César D. Rodas
    - email: crodas@php.net

preferGlobal: true

bin:
    autoloader: cli.php

files: [lib],
version: 0.1.1-dev

dependencies:
    - https://github.com/symfony/Console
    - https://github.com/symfony/Finder
    - https://github.com/crodas/Artifex
    - https://github.com/crodas/Notoj
