name: autoloader
authors:
    - name: César D. Rodas
    - email: crodas@php.net

preferGlobal: true

bin:
    autoloader: cli.php

files: [lib],
version: 0.1.1-dev

dependencies:
    - github:symfony/Console
    - github:symfony/Finder
    - github:crodas/Artifex
    - github:crodas/Notoj
